spring.application.name=SpringBootAlarkoOrnek
spring.datasource.url=jdbc:postgresql://localhost:5433/BoostDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix:.jsp
server.port=8095
springdoc.swagger-ui.path=/swagger-ui.html
#spring.mvc.view.prefix:/templates
#spring.mvc.view.suffix:.html
